ktor:
    development: true
    application:
        modules:
            - com.debugdesk.superheros.ApplicationKt.module
    deployment:
        port: 8080, ${?PORT}
        watch: [ classes, resources ]
